# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmokeTest():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")

    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_01CommonBrowserTab(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1190, 3000)
    assert self.driver.title == "Teton Idaho CoC"
  
  def test_02CommonLogo(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
  
  def test_03CommonWebsiteHeading(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
  
  def test_04HomePageJoinUsLinkPresent(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us")
    assert len(elements) > 0
  
  def test_05HomePage2SpotlightsPresent(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1")
    assert len(elements) > 0
  
  def test_06HomePageJoinUsLinkGoesToJoinPage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    self.vars["currentPath"] = self.driver.execute_script("return window.location.pathname;")
    assert(self.vars["currentPath"] == "/teton/1.6/join.html")
  
  def test_07DirectoryGridViewTurfBusinessPresent(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.find_element(By.LINK_TEXT, "Directory").click()
    self.driver.find_element(By.ID, "directory-grid").click()
    assert self.driver.find_element(By.XPATH, "//p[contains(.,\'Teton Turf and Tree\')]").text == "Teton Turf and Tree"
  
  def test_08DirectoryListViewTurfBusinessPresent(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.find_element(By.LINK_TEXT, "Directory").click()
    self.driver.find_element(By.ID, "directory-list").click()
    assert self.driver.find_element(By.XPATH, "//p[contains(.,\'Teton Turf and Tree\')]").text == "Teton Turf and Tree"
  
  def test_09JoinPageFirstNameBoxPresent(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.find_element(By.LINK_TEXT, "Join").click()
    elements = self.driver.find_elements(By.NAME, "fname")
    assert len(elements) > 0
  
  def test_10JoinPageFillFormNextEmailBoxPresent(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.find_element(By.LINK_TEXT, "Join").click()

    self.driver.find_element(By.NAME, "fname").send_keys("Tester")
    self.driver.find_element(By.NAME, "lname").send_keys("McTester")
    self.driver.find_element(By.NAME, "bizname").send_keys("Tester Inc")
    self.driver.find_element(By.NAME, "biztitle").send_keys("CEO")

    self.driver.find_element(By.NAME, "submit").click()

    elements = self.driver.find_elements(By.NAME, "email")
    assert len(elements) > 0
  
  def test_11AdminUsernameBoxPresent(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.find_element(By.LINK_TEXT, "Admin").click()
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
  
  def test_12AdminBadInputSubmitError(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.find_element(By.LINK_TEXT, "Admin").click()

    self.driver.find_element(By.ID, "username").send_keys("wrongtester")
    self.driver.find_element(By.ID, "password").send_keys("wrongpassword")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit").click()

    elements = self.driver.find_elements(By.CSS_SELECTOR, ".errorMessage")
    assert len(elements) > 0
  
